name: Build iOS app

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    
env:
    DOTNETVERSION: 8.0.303
    MAUIFRAMEWORK: net8.0-ios
    PROJECTNAME: Skolplattformen.ElevApp
    APPLICATIONID: se.kolplattformen.elevapp
    
jobs:
  buildIOS:
      runs-on: macos-latest
      env:
          BUILDNUMBER: $(expr ${{ github.run_number }} + 16)

      steps:
        - uses: actions/checkout@v3
        
        - name: Install fastlane
          run: |
            brew install fastlane

        - name: Setup provisioning
          env:
            MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
            MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          run: |
            fastlane match development --readonly

        - name: Setup .NET SDK
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '${{env.DOTNETVERSION}}'

        - name: Install .NET MAUI
          run: |
            dotnet workload install maui-ios

        - name: Build iOS App
          run: |
            cd src/${{env.PROJECTNAME}}
            dotnet publish -f:${{env.MAUIFRAMEWORK}} -c:Release \
              /p:BuildIpa=true \
              /p:RuntimeIdentifier=ios-arm64 \
              /p:ApplicationId=${{env.APPLICATIONID}}

        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
            name: ios-build
            path: src/${{env.PROJECTNAME}}/bin/Release/${{env.MAUIFRAMEWORK}}/ios-arm64/publish/*.ipa
